import React,{useState,useEffect}from'react';import api from'../services/api';import Modal from'../components/Modal';import DetailPanel from'../components/DetailPanel';
export default function AccountsPage(){const[items,setItems]=useState([]),[sel,setSel]=useState(null),[modal,setModal]=useState(false),[form,setForm]=useState({name:'',institution:'',account_type:'checking',balance:0});
useEffect(()=>{load()},[]);const load=()=>api.getAccounts().then(setItems);
const submit=async e=>{e.preventDefault();await api.createAccount(form);setModal(false);load()};
const del=async()=>{if(window.confirm('Delete?')){await api.deleteAccount(sel.id);setSel(null);load()}};
const fmt=n=>Number(n)>=0?`$${Number(n).toLocaleString('en',{minimumFractionDigits:2})}`:`-$${Math.abs(Number(n)).toLocaleString('en',{minimumFractionDigits:2})}`;
const inp={width:'100%',padding:'10px 14px',background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:8,color:'#e0e0e0',fontSize:14,marginBottom:12,outline:'none'};
return(<div style={{padding:30}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><h1 style={{fontSize:24,color:'#e0e0e0'}}>Accounts</h1><button style={{padding:'10px 20px',background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={()=>setModal(true)}>+ Add Account</button></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:16}}>{items.map(a=><div key={a.id} style={{background:'#16213e',borderRadius:12,padding:20,border:'1px solid #0f3460',cursor:'pointer'}} onClick={()=>setSel(a)}><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><div><div style={{fontSize:16,fontWeight:'bold',color:'#e0e0e0'}}>{a.name}</div><div style={{fontSize:12,color:'#a0a0b0'}}>{a.institution}</div></div><span style={{padding:'4px 10px',borderRadius:12,fontSize:11,background:a.account_type==='credit'?'#e9456020':a.account_type==='investment'?'#9b59b620':'#2ecc7120',color:a.account_type==='credit'?'#e94560':a.account_type==='investment'?'#9b59b6':'#2ecc71'}}>{a.account_type}</span></div><div style={{fontSize:24,fontWeight:'bold',color:Number(a.balance)>=0?'#2ecc71':'#e94560'}}>{fmt(a.balance)}</div></div>)}</div>
<Modal isOpen={modal} onClose={()=>setModal(false)} title="Add Account"><form onSubmit={submit}>{[['Account Name','name'],['Institution','institution'],['Balance','balance']].map(([l,k])=><div key={k}><label style={{color:'#a0a0b0',fontSize:12}}>{l}</label><input style={inp} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required/></div>)}<select style={inp} value={form.account_type} onChange={e=>setForm({...form,account_type:e.target.value})}><option value="checking">Checking</option><option value="savings">Savings</option><option value="credit">Credit Card</option><option value="investment">Investment</option></select><button style={{width:'100%',padding:12,background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} type="submit">Add Account</button></form></Modal>
<DetailPanel isOpen={!!sel} onClose={()=>setSel(null)} title="Account Details">{sel&&<>{[['Name',sel.name],['Institution',sel.institution],['Type',sel.account_type],['Balance',fmt(sel.balance)],['Account #',sel.account_number]].map(([l,v])=><div key={l} style={{marginBottom:16}}><div style={{color:'#a0a0b0',fontSize:12}}>{l}</div><div style={{color:'#e0e0e0',fontSize:14}}>{v}</div></div>)}<button style={{width:'100%',padding:10,background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={del}>🗑️ Delete Account</button></>}</DetailPanel></div>)}
