import React,{useState}from'react';import api from'../services/api';
export default function AgentsPage(){const[tab,setTab]=useState('spending'),[input,setInput]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false);
const run=async fn=>{setLoading(true);setResult(null);try{setResult(await fn())}catch(e){setResult({error:e.message})}setLoading(false)};
const renderResult=(obj,d=0)=>{if(!obj)return null;if(typeof obj==='string')return<p style={{color:'#e0e0e0',lineHeight:1.6,whiteSpace:'pre-wrap'}}>{obj}</p>;if(Array.isArray(obj))return<div style={{marginLeft:d*12}}>{obj.map((item,i)=><div key={i} style={{background:'#1a1a2e',padding:12,borderRadius:8,marginBottom:8,borderLeft:'3px solid #e94560'}}>{typeof item==='object'?renderResult(item,d+1):<span style={{color:'#e0e0e0'}}>{String(item)}</span>}</div>)}</div>;return<div style={{marginLeft:d*12}}>{Object.entries(obj).map(([k,v])=><div key={k} style={{marginBottom:12}}><div style={{color:'#e94560',fontSize:13,fontWeight:'bold',textTransform:'uppercase',marginBottom:4}}>{k.replace(/_/g,' ')}</div>{typeof v==='object'&&v!==null?renderResult(v,d+1):<div style={{color:'#e0e0e0',background:'#1a1a2e',padding:'8px 12px',borderRadius:6,fontSize:14}}>{typeof v==='number'?<span style={{color:'#2ecc71',fontWeight:'bold',fontSize:18}}>{v}</span>:String(v)}</div>}</div>)}</div>;};
const inp={width:'100%',padding:'10px 14px',background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:8,color:'#e0e0e0',fontSize:14,marginBottom:12,outline:'none',minHeight:100,resize:'vertical',fontFamily:'inherit'};
return(<div style={{padding:30}}><h1 style={{fontSize:24,color:'#e0e0e0',marginBottom:24}}>AI Agents</h1><div style={{display:'flex',gap:4,marginBottom:24}}>{[['spending','📊 Spending Analyzer'],['savings','💰 Savings Finder'],['forecast','🔮 Spending Forecast']].map(([k,l])=><button key={k} style={{padding:'10px 20px',background:tab===k?'#e94560':'#16213e',color:tab===k?'#fff':'#a0a0b0',border:'none',borderRadius:'8px 8px 0 0',cursor:'pointer',fontSize:14,fontWeight:tab===k?'bold':'normal'}} onClick={()=>{setTab(k);setResult(null)}}>{l}</button>)}</div>
<div style={{background:'#16213e',borderRadius:12,padding:24,border:'1px solid #0f3460'}}>{tab==='spending'&&<><label style={{color:'#a0a0b0',fontSize:12}}>Transaction Data (JSON or describe your spending)</label><textarea style={inp} value={input} onChange={e=>setInput(e.target.value)} placeholder='Describe your spending patterns or paste transaction data...'/><button style={{padding:'12px 24px',background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={()=>run(()=>api.analyzeSpending({transactions:input}))} disabled={loading}>{loading?'⏳ Analyzing...':'📊 Analyze Spending'}</button></>}
{tab==='savings'&&<><label style={{color:'#a0a0b0',fontSize:12}}>Financial Data</label><textarea style={inp} value={input} onChange={e=>setInput(e.target.value)} placeholder='List your subscriptions, recurring bills, spending habits...'/><button style={{padding:'12px 24px',background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={()=>run(()=>api.detectSavings({data:input}))} disabled={loading}>{loading?'⏳ Finding...':'💰 Find Savings'}</button></>}
{tab==='forecast'&&<><label style={{color:'#a0a0b0',fontSize:12}}>Spending History</label><textarea style={inp} value={input} onChange={e=>setInput(e.target.value)} placeholder='Describe your monthly spending history...'/><button style={{padding:'12px 24px',background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={()=>run(()=>api.forecast({history:input}))} disabled={loading}>{loading?'⏳ Forecasting...':'🔮 Forecast'}</button></>}</div>
{result&&<div style={{marginTop:24,background:'#16213e',borderRadius:12,padding:24,border:'1px solid #0f3460'}}><div style={{color:'#e94560',fontSize:16,fontWeight:'bold',marginBottom:16,paddingBottom:12,borderBottom:'1px solid #0f3460'}}>🤖 AI Analysis</div>{result.error?<div style={{color:'#e94560'}}>{result.error}</div>:renderResult(result)}</div>}</div>)}
