import React,{useState,useEffect}from'react';import api from'../services/api';import Modal from'../components/Modal';
export default function BudgetsPage(){const[items,setItems]=useState([]),[modal,setModal]=useState(false),[form,setForm]=useState({category:'',monthly_limit:''});
useEffect(()=>{load()},[]);const load=()=>api.getBudgets().then(setItems);
const submit=async e=>{e.preventDefault();await api.createBudget(form);setModal(false);load()};
const pct=b=>Math.min(100,Math.round(b.spent/b.monthly_limit*100));
const color=p=>p>90?'#e94560':p>75?'#f39c12':'#2ecc71';
const inp={width:'100%',padding:'10px 14px',background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:8,color:'#e0e0e0',fontSize:14,marginBottom:12,outline:'none'};
return(<div style={{padding:30}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><h1 style={{fontSize:24,color:'#e0e0e0'}}>Budgets</h1><button style={{padding:'10px 20px',background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={()=>setModal(true)}>+ Add Budget</button></div>
<div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:16}}>{items.map(b=>{const p=pct(b);const c=color(p);return<div key={b.id} style={{background:'#16213e',borderRadius:12,padding:20,border:'1px solid #0f3460'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><div style={{fontSize:16,fontWeight:'bold',color:'#e0e0e0'}}>{b.category}</div><span style={{color:c,fontWeight:'bold'}}>{p}%</span></div><div style={{background:'#1a1a2e',borderRadius:8,height:12,overflow:'hidden',marginBottom:8}}><div style={{background:c,height:'100%',width:`${p}%`,borderRadius:8,transition:'width 0.3s'}}/></div><div style={{display:'flex',justifyContent:'space-between',fontSize:13}}><span style={{color:'#a0a0b0'}}>Spent: <span style={{color:c}}>${Number(b.spent).toFixed(0)}</span></span><span style={{color:'#a0a0b0'}}>Limit: ${Number(b.monthly_limit).toFixed(0)}</span></div></div>})}</div>
<Modal isOpen={modal} onClose={()=>setModal(false)} title="Add Budget"><form onSubmit={submit}><label style={{color:'#a0a0b0',fontSize:12}}>Category</label><input style={inp} value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/><label style={{color:'#a0a0b0',fontSize:12}}>Monthly Limit ($)</label><input style={inp} type="number" value={form.monthly_limit} onChange={e=>setForm({...form,monthly_limit:e.target.value})} required/><button style={{width:'100%',padding:12,background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} type="submit">Add Budget</button></form></Modal></div>)}
